name: github-firebot


on:
  push:
    branches:
      - github-firebot
    paths:
      - .github/workflows/firebot.yml
      - Build/**
      - Source/**
  schedule:
    # run every night at 12:30am EST (4:30 am UTC)
    # * is a special character in YAML so you have to quote this string
    - cron: '30 4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# concurrency:
#   group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: ${{ github.event_name == 'pull_request' }}

# permissions:
#   contents: read

jobs:
  build-run:
    # build on ubuntu using ifort with intelmpi and mkl based on
    # https://github.com/oneapi-src/oneapi-ci

    name: compile and run fds
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

      # install oneapi components from apt repository based on
      # oneapi-ci/scripts/setup_apt_repo_linux.sh
      # oneapi-ci/scripts/apt_depends.sh
      # oneapi-ci/scripts/install_linux_apt.sh
    - name: setup apt repository
      run: |
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/oneAPI.list" -o APT::Get::List-Cleanup="0"
    - name: collect versioned dependencies of apt packages
      run : |
        apt-cache depends intel-oneapi-compiler-fortran \
                          intel-oneapi-mpi-devel \
                          intel-oneapi-mkl-devel | tee dependencies.txt
    - name: cache install oneapi
      id: cache-install
      uses: actions/cache@v3
      with:
        path: /opt/intel/oneapi
        key: install-${{ hashFiles('**/dependencies.txt') }}
    - name: install oneapi compiler, mpi, mkl
      if: steps.cache-install.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install -y intel-oneapi-compiler-fortran \
                                intel-oneapi-mpi-devel \
                                intel-oneapi-mkl-devel
        sudo apt-get clean

    - name: build fds debug
      run: |
        source /opt/intel/oneapi/setvars.sh
        cd ./Build/impi_intel_linux_db
        sh ./make_fds.sh
        ./fds_impi_intel_linux_db
    # - name: build fds release
    #   run: |
    #     source /opt/intel/oneapi/setvars.sh
    #     cd ./Build/impi_intel_linux
    #     sh ./make_fds.sh
    #     ./fds_impi_intel_linux

    - name: run a case
      run: |
        cd $GITHUB_WORKSPACE/Verification/Fires
        $GITHUB_WORKSPACE/Build/impi_intel_linux_db/fds_impi_intel_linux_db simple_test.fds



